[wokwi]
version = 1
elf = "mohan/build/build/oled/.pioenvs/oled/firmware.elf"
firmware = "mohan/build/build/oled/.pioenvs/oled/firmware.bin"
gdbServerPort=3333

# Forward http://localhost:8180 to port 80 on the simulated ESP32:
[[net.forward]]
from = "localhost:8180"
to = "10.13.37.2:80"