esphome:
  name: ili9341
esp32:
  board: esp32-s3-devkitc-1 
wifi:
  ssid: Wokwi-GUEST
web_server:
logger:
spi:
  clk_pin: GPIO14
  mosi_pin: GPIO13
  miso_pin: GPIO12
color:
  - id: my_red
    red: 100%
    green: 3%
    blue: 5%
display:
  - platform: ili9xxx
    model: TFT 2.4
    cs_pin: GPIO26
    dc_pin: GPIO25
    reset_pin: GPIO33
    rotation: 90°
    lambda: |-
      it.rectangle(0,  0, it.get_width(), it.get_height(), id(my_red));
    
